name: "Destroy infra"
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options: 
        - dev
        - prod
env:
  TERRAFORM_PATH: "terraform/env/${{ inputs.environment }}"
  TF_VAR_db_name: ""
  TF_VAR_db_password: ""
  TF_VAR_db_username: ""
jobs:
  destroi_infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.3"

      - name: Terraform Init
        id: init
        run: terraform -chdir=$TERRAFORM_PATH init
        
      - name: Terraform destroy
        run: terraform -chdir=$TERRAFORM_PATH destroy -auto-approve
