name: "Criação de Infraestrutura básica para as aplicações"
on:
  push:
    branches: [main, develop]   # Aceita push em qualquer branch
  pull_request:
env:
  AMBIENTE: ${{ (github.ref_name == 'main' || github.event_name == 'pull_request') && 'prod' || 'dev' }}
  TF_VAR_bd_senha: ${{ secrets.DB_PASSWORD }}
  TF_VAR_bd_usuario: ${{ secrets.DB_USER }}
  TF_VAR_bd_nome:  ${{ vars.DB_NAME }}
jobs:
  cria_infra:
    name: "Criação de infra para aplicações do techchallenge"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4.2.2
      
      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Realiza setup do Terraform
        run: ./terraform/setup.sh

      - name: Setup do Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.3"
          terraform_wrapper: false # Configuração para permiter acesso aos outputs do terraform

      - name: Terraform Format
        id: fmt
        run: terraform -chdir=terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform -chdir=terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform -chdir=terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request' || github.ref_name == 'develop'
        run: terraform -chdir=terraform plan -var "ambiente=$AMBIENTE" -no-color -input=false
        continue-on-error: true

      - name: Atualização do Pull Request
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        env:
          PLAN: ${{ steps.plan.outputs.stdout }}
        with:
          script: |
            const output = `#### Terraform - Formatação e Estilo 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Init ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validação 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Detalhes do Terraform Plan</summary>

            \`\`\`terraform\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Enviado por: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: (github.ref_name == 'main' || github.ref_name == 'develop') && github.event_name == 'push'
        run: terraform -chdir=terraform apply -var "ambiente=$AMBIENTE" -auto-approve -input=false
      
      - name: Export Terraform outputs
        id: tf
        run: |
          echo "BD_HOST=$(terraform output -raw bd_host)" >> $GITHUB_ENV
        working-directory: ./terraform
      
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
      
      - name: Wait for DB to be available        
        run: |
          echo "Aguardando o banco de dados ficar disponível..."          
          
          # Tentar conexão até que seja possível
          until PGPASSWORD=$TF_VAR_bd_senha psql -h $BD_HOST -U $TF_VAR_bd_usuario -d $TF_VAR_bd_nome -p 5432 -c "SELECT 1" > /dev/null 2>&1; do
            echo "DB ainda não está disponível, aguardando 10 segundos..."
            sleep 10
          done
          echo "Banco de dados está pronto!"
      
      - name: Run initialization scripts
        run: |
          echo "Executando scripts de inicialização..."
          # Execute DDL
          PGPASSWORD=$TF_VAR_bd_senha psql -h $BD_HOST -U $TF_VAR_bd_usuario -d $TF_VAR_bd_nome -p 5432 -f ./database/01.sql
          
          # Execute DML 
          PGPASSWORD=$TF_VAR_bd_senha psql -h $BD_HOST -U $TF_VAR_bd_usuario -d $TF_VAR_bd_nome -p 5432 -f ./database/02.sql
          
          echo "Inicialização concluída!"